
[project]
name = "example"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["numpy~=2.3"]


[tool.maturin]
module-name = "example._core"
python-packages = ["example"]
python-source = "src"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
